# Week 4A: Introduction to `numpy`

<font color='blue'><b>Goals of this notebook:</b></font>
Learn to use `numpy` (short for numeric python) to compute matrix multiplications in the optimization algorithms in our course.

<font color='blue'><b>Python packages required:</b></font>
`numpy` might have been already installed on your computer. You can try executing `import numpy as np` in the first code box; if it does not work, please install `numpy` using the following commands:
- using `pip`: `pip install numpy` <br>
- using `Anaconda`: `conda install numpy`

<font color='blue'><b>Additional resources:</b></font> For us, `numpy` is mostly a tool to compute matrix multiplications. However, `numpy` allows for a wide range of scientific computations. For more information, please refer to its official user guide: https://numpy.org/doc/stable/user/.


In [1]:
# Import the package
import numpy as np

### Feeding a matrix to `numpy`
The following code shows how to store the matrix
$$A:=\begin{bmatrix}1&3\\4&5\end{bmatrix}$$
in `numpy`: as a list of lists which correspond to the row vectors of $A$.

In [2]:
A = np.matrix([
    [1,3],
    [4,5]
])

A

matrix([[1, 3],
        [4, 5]])

### Matrix multiplication
Consider $B:=\begin{bmatrix}1&5&4\\6&9&0\end{bmatrix}$. Then $A\cdot B$ is computed in `numpy` via the `matmul` function:

In [3]:
B = np.matrix([
    [1,5,4],
    [6,9,0]
])

np.matmul(A,B)

matrix([[19, 32,  4],
        [34, 65, 16]])

### Matrix transposes
To calculate $A^T$, use the `np.transpose` function:

In [4]:
np.transpose(A)

matrix([[1, 4],
        [3, 5]])

### Working with matrix inverses
The inverse $A^{-1}$ of $A$ can be calculated using `linalg.inv`.

*Note: Using the inverse explicitly can lead to numerical instabilities. We will try to avoid it if possible and use "work-araounds". For example, to get the solution for a system of form $A=xB$, we don't compute $x$ by $x = A^{-1}B$ but instead use the numpy function `linalg.solve`.*

In [5]:
A_inv = np.linalg.inv(A)

print("Inverse of A:")
print(A_inv, "\n")

print("inv(A)⋅B:")
print(np.matmul(A_inv, B), "\n")

print("Solve for x in A = xB:")
print(np.linalg.solve(A,B))

Inverse of A:
[[-0.71428571  0.42857143]
 [ 0.57142857 -0.14285714]] 

inv(A)⋅B:
[[ 1.85714286  0.28571429 -2.85714286]
 [-0.28571429  1.57142857  2.28571429]] 

Solve for x in A = xB:
[[ 1.85714286  0.28571429 -2.85714286]
 [-0.28571429  1.57142857  2.28571429]]


Here we don't see a difference, as $A$ isn't ill-condidioned. You can try to find an ill-conditioned $A$ where using the direct inverse gives you a different solution to $x$ as using `linalg.solve`. 

### Row/column manipulation using `numpy`

Note that the index in Python starts from 0. <br>
To access the $i$-th row in the matrix $A$, we use the following command: `A[i-1,:]`. <br>
Similarly, to access the $j$-th column, we use: `A[:,j-1]`.

In [6]:
# First row of A
print("First row of A:")
print(A[0,:], "\n")

# Second column of A
print("Second column of A:")
print(A[:,1])

First row of A:
[[1 3]] 

Second column of A:
[[3]
 [5]]


### Number of rows and columns in a matrix
To get the number of **rows** in a matrix, use: `A.shape[0]`.<br>
To get the number of **columns** in a matrix, use: `A.shape[1]`.<br>
Here we use matrix $B$ as an example.

In [7]:
# Rows and columns
print("Rows: " + str(B.shape[0]))
print("Columns: " + str(B.shape[1]))

Rows: 2
Columns: 3


### Accessing elements of the matrix
To get the element $a_{i,j}$ in the matrix $A$, we use: `A[i-1,j-1]`. 

In [8]:
# Element in first row, second column
a_12 = A[0,1]
print(a_12)

3
